# Generated by Django 5.1 on 2024-09-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='certificate',
            field=models.CharField(choices=[('U', 'U'), ('PG', 'PG'), ('12a', '12a'), ('15', '15'), ('18', '18')], max_length=3),
        ),
    ]
