# Generated by Django 5.1 on 2024-09-18 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='store1/img/'),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='store1/thmb/'),
        ),
    ]
