# Generated by Django 5.1 on 2024-10-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(db_index=True, max_length=30)),
                ('model', models.CharField(db_index=True, max_length=30)),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('make', 'model'),
                'constraints': [models.UniqueConstraint(fields=('make', 'model'), name='unique_attr')],
            },
        ),
    ]
