# Generated by Django 5.1 on 2024-10-03 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cars',
            new_name='Car',
        ),
    ]
