# Generated by Django 5.1 on 2024-11-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regis2', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='like',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
