# Generated by Django 5.1 on 2024-11-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regis2', '0003_book_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='like',
            field=models.BooleanField(null=True),
        ),
    ]
